language: go

branches:
    only:
        - master

os:
    - linux
    - osx

env:
    - GO111MODULE=on

go:
    - 1.12.9
    - 1.13

git:
    depth: 1
    submodules: false

script:
    - go test -v -cover  ./...
